CXX = c++
CXX_FLAGS = -pedantic -g -std=c++17

SRC_DIR = src
TEST_DIR = misc
HDR_DIR = include
BUILD_DIR = build

HDRS = $(shell find $(HDR_DIR) -name "*.h")

SRCS = $(shell find $(SRC_DIR) -name "*.cpp")
TEST_SRCS_STRIPPED = $(shell find $(TEST_DIR) -name "*.cpp" -exec basename \{} \;)
TEST_SRCS = $(addprefix $(TEST_DIR)/, $(TEST_SRCS_STRIPPED))

OBJ = $(addprefix $(BUILD_DIR)/, $(patsubst %.cpp,%.o,$(SRCS)))
TEST_OBJ = $(addprefix $(BUILD_DIR)/, $(patsubst %.cpp,%.o,$(TEST_SRCS)))
TEST_BIN = $(patsubst %.cpp,%.out,$(TEST_SRCS_STRIPPED))

all: $(TEST_BIN)

$(OBJ): $(BUILD_DIR)/%.o : %.cpp $(HDRS)
	mkdir -p $(@D)
	$(CXX) $(CXX_FLAGS) -c -I $(HDR_DIR) -o $@ $<

$(TEST_OBJ): $(BUILD_DIR)/%.o : %.cpp
	mkdir -p $(@D)
	$(CXX) $(CXX_FLAGS) -c -I $(HDR_DIR) -o $@ $<

$(TEST_BIN): %.out : $(BUILD_DIR)/$(TEST_DIR)/%.o $(OBJ)
	$(CXX) $(CXX_FLAGS) -lpthread -I $(HDR_DIR) -o $@ $< $(OBJ)

.PHONY: clean
clean:
	rm -rf build/
	rm -rf *.dSYM/
	rm -f *.out

